version: "3"
services:
  client:
    container_name: task-client
    build:
      context: ./client
    working_dir: /app
    volumes:
      - ./client/src:/app/src
      - ./client/.svelte-kit:/app/.svelte-kit
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    container_name: task-server
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./server/src:/app
    ports:
      - 8080:8080
    command: air ./main.go -b 0.0.0.0:8080
